### ISSUE TITLE
rstudio fails to start

### ISSUE THREAD

**Issue by ilikegitlab** [jgenco/jgenco-overlay#15]
Hi,

updated today and I see this after starting rstudio:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at exports.getFileName (/usr/share/rstudio/resources/app/.webpack/main/index.js:8:46679)
    at bindings (/usr/share/rstudio/resources/app/.webpack/main/index.js:8:45703)
    at 7981 (/usr/share/rstudio/resources/app/.webpack/main/index.js:8:179867)
    at __webpack_require__ (/usr/share/rstudio/resources/app/.webpack/main/index.js:19:181562)
    at 9525 (/usr/share/rstudio/resources/app/.webpack/main/index.js:19:7093)
    at __webpack_require__ (/usr/share/rstudio/resources/app/.webpack/main/index.js:19:181562)
    at 155 (/usr/share/rstudio/resources/app/.webpack/main/index.js:8:382802)
    at __webpack_require__ (/usr/share/rstudio/resources/app/.webpack/main/index.js:19:181562)
    at 3585 (/usr/share/rstudio/resources/app/.webpack/main/index.js:19:36879)
    at __webpack_require__ (/usr/share/rstudio/resources/app/.webpack/main/index.js:19:181562)

let me know if I can do anything to help debug.

**Comment by ilikegitlab** [comment]
ok. I downgraded nodejs (had 20.5 installed), recompiled, and now it works.

**Comment by ilikegitlab** [comment]
18.16.0 works.
I noticed that first the compile failed because with 20.5.0, it couldn't find node-gyp-bin (location changed), that was easy to fix by a hackish symlink. I'm not sure the problem was related to that though.

**Comment by jgenco** [comment]
I currently have nodejs-20.2.0 (the newest stable release) installed and it worked fine for me.  So, I have added `<net-libs/nodejs-20.3.0` to rstudio-2023.06.1.524 and rstudio-2023.09.0.199.

**Comment by jgenco** [comment]
Hello, I accidentally came across Gentoo bug [912037: ...net-lids/nodejs-20.5.1 stable request](https://bugs.gentoo.org/show_bug.cgi?id=912037), which wants to stabilize a set of nodejs versions because of a [security problem](https://github.com/nodejs/node/releases/tag/v20.5.1).  I was wondering if you could try installing `rstudio-2023.09.0.301`  and see if it works.  I have tested 20.2.0 and 20.5.1 but I haven't tested 18 yet.

Note: You can use `quickpkg rstudio` to save your current rstudio install and reinstall it if need be.

**Comment by ilikegitlab** [comment]
hmm, I haven't much time at the moment so didn't report back yet. I'll try tomorrow.

**Comment by ilikegitlab** [comment]
Ok. 2023.09.0.301 compiles and starts with either nodejs 18.16.0 or with 20.5.1.

**Comment by jgenco** [comment]
Great, thanks for testing. I can't see how you got that far, so I wanted to be sure there wasn't something I was missing with regards to using `>=nodejs20.5`.
