### ISSUE TITLE
IUSE flags made me to to enable electron

### ISSUE THREAD

**Issue by mmokrejs** [jgenco/jgenco-overlay#16]
Hi,
  I wonder how to get compiled the desktop application. I do not need/want rstudio-server. But, the USE flags are somehow twisted.

```
!!! The ebuild selected to satisfy "rstudio" has unmet requirements.
- sci-mathematics/rstudio-2023.06.1.524::jgenco USE="(prefix) -clang -debug -doc -electron -panmirror -qt5 -qt6 -quarto -server -test"

  The following REQUIRED_USE flag constraints are unsatisfied:
    !server? ( exactly-one-of ( electron qt5 qt6 ) )
```

I cannot get compiled `qt5` nor `qt6` at the moment. Is there any way out for me?

I enabled `electron` but rstudio refuses to start because this is a Gentoo-Prefix installation on a computer cluster where I have no root privs. Therefore, I cannot even create an SUID to root binary.

```
$ rstudio 
[680196:0808/114826.400190:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /auto/vestec1-elixir/projects/biocev/gentoo/usr/share/rstudio/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
$
```

**Comment by jgenco** [comment]
It  looks like there are a couple issues here.

### IUSE
I haven't come up a simple IUSE for RStudio yet, but the simple English version is `server and/or GUI` with GUI being only one of `qt5, qt6, or electron`.  When multiple GUIs are selected (`+server`) the order of preference is electron, qt6, qt5.
With a couple caveats.
* `+electron +server` is not supported by upstream
* `qt6` is a patch of my own design 
* `qt5` will eventually be drop upstream

### Prefix
I don't use Prefix installation so I don't know how much help I can give on such a system.

### Setuid
You can try running `rstudio  --no-sandbox` or `rstudio --disable-setuid-sandbox`.

It is curious  when I `stat /usr/share/rstudio/chrome-sandbox` i get
```
  File: /usr/share/rstudio/chrome-sandbox
  Size: 14888           Blocks: 32         IO Block: 4096   regular file
Device: 0,17    Inode: 88682020    Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
```
It looks like Electron tries to uses [Linux namespaces](https://en.wikipedia.org/wiki/Linux_namespaces) (specifically `CONFIG_USER_NS=y`) first before falling back to SUID.

### QT problems
I'm curious about qt problems you have.  Note: I haven't test the QT6 patch with `qt-6.5.2`.  I think the last qt6 version I've test it with is `qt-6.5.0-r2`

**Comment by mmokrejs** [comment]
Hi, thank you for a detailed answer. Gentoo::Prefix installation allows you to run Gentoo on almost any UNIX with your own libc and tools under your own UID. You do not have root or other users under it, so you cannot have SUID binaries set to some other user.  I never heard of electron before but it seems `electron` just cannot be used under Gentoo::Prefix, by design.
With Gentoo::Prefix you use only on the host kernel. The installation uses a modified loader to load libs for the binaries executed. So, in the case below it seems the `rstudio` build process correctly picked the Gentoo::Prefix `libc` but during execution somehow the host `libc` is called, and that fails.

Here is what I get:

```
$ rstudio --no-sandbox
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /auto/vestec1-elixir/projects/biocev/gentoo/usr/share/rstudio/resources/app/.webpack/main/native_modules/desktop.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 7052 (/auto/vestec1-elixir/projects/biocev/gentoo/usr/share/rstudio/resources/app/.webpack/main/index.js:8:355741)
    at __webpack_require__ (/auto/vestec1-elixir/projects/biocev/gentoo/usr/share/rstudio/resources/app/.webpack/main/index.js:19:181562)
[707132:0808/174425.544358:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[707132:0808/174425.544476:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[707162:0808/174425.829432:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[707206:0808/174425.936493:ERROR:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
```

and I do NOT see the app window anywhere.

```
$ whereis rstudio
rstudio: /auto/vestec1-elixir/projects/biocev/gentoo/usr/bin/rstudio
$ ldd /auto/vestec1-elixir/projects/biocev/gentoo/usr/bin/rstudio
	linux-vdso.so.1 (0x00007ffd7ed85000)
	libffmpeg.so => not found
	libdl.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/lib64/libdl.so.2 (0x00007f9d633e1000)
	libpthread.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/lib64/libpthread.so.0 (0x00007f9d633dc000)
	libgobject-2.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgobject-2.0.so.0 (0x00007f9d6337b000)
	libglib-2.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libglib-2.0.so.0 (0x00007f9d63237000)
	libgio-2.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgio-2.0.so.0 (0x00007f9d63053000)
	libnss3.so => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libnss3.so (0x00007f9d62f1b000)
	libnssutil3.so => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libnssutil3.so (0x00007f9d62ee9000)
	libsmime3.so => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libsmime3.so (0x00007f9d62ec0000)
	libnspr4.so => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libnspr4.so (0x00007f9d62e7e000)
	libatk-1.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libatk-1.0.so.0 (0x00007f9d62e54000)
	libatk-bridge-2.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libatk-bridge-2.0.so.0 (0x00007f9d62e18000)
	libcups.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libcups.so.2 (0x00007f9d62d7a000)
	libdbus-1.so.3 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libdbus-1.so.3 (0x00007f9d62d2d000)
	libdrm.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libdrm.so.2 (0x00007f9d62d16000)
	libgtk-3.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgtk-3.so.0 (0x00007f9d62537000)
	libpango-1.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libpango-1.0.so.0 (0x00007f9d624cd000)
	libcairo.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libcairo.so.2 (0x00007f9d6238c000)
	libX11.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libX11.so.6 (0x00007f9d62241000)
	libXcomposite.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXcomposite.so.1 (0x00007f9d6223c000)
	libXdamage.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXdamage.so.1 (0x00007f9d62235000)
	libXext.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXext.so.6 (0x00007f9d6221f000)
	libXfixes.so.3 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXfixes.so.3 (0x00007f9d62217000)
	libXrandr.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXrandr.so.2 (0x00007f9d6220a000)
	libgbm.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgbm.so.1 (0x00007f9d621f9000)
	libexpat.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libexpat.so.1 (0x00007f9d621cc000)
	libxcb.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libxcb.so.1 (0x00007f9d621a1000)
	libxkbcommon.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libxkbcommon.so.0 (0x00007f9d6215a000)
	libasound.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libasound.so.2 (0x00007f9d6206a000)
	libatspi.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libatspi.so.0 (0x00007f9d6202f000)
	libm.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/lib64/libm.so.6 (0x00007f9d61f4f000)
	libgcc_s.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/13/libgcc_s.so.1 (0x00007f9d61f29000)
	libc.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/lib64/libc.so.6 (0x00007f9d61d56000)
	/lib64/ld-linux-x86-64.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/lib64/ld-linux-x86-64.so.2 (0x00007f9d6d274000)
	libffi.so.8 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libffi.so.8 (0x00007f9d61d4a000)
	libpcre2-8.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libpcre2-8.so.0 (0x00007f9d61cae000)
	libgmodule-2.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgmodule-2.0.so.0 (0x00007f9d61ca7000)
	libz.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libz.so.1 (0x00007f9d61c8a000)
	libmount.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libmount.so.1 (0x00007f9d61c1d000)
	libplc4.so => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libplc4.so (0x00007f9d61c16000)
	libplds4.so => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libplds4.so (0x00007f9d61c11000)
	libssl.so.3 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libssl.so.3 (0x00007f9d61b6c000)
	libcrypto.so.3 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libcrypto.so.3 (0x00007f9d61686000)
	libgdk-3.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgdk-3.so.0 (0x00007f9d61593000)
	libpangocairo-1.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libpangocairo-1.0.so.0 (0x00007f9d61582000)
	libharfbuzz.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libharfbuzz.so.0 (0x00007f9d61451000)
	libpangoft2-1.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libpangoft2-1.0.so.0 (0x00007f9d61438000)
	libfontconfig.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libfontconfig.so.1 (0x00007f9d613e9000)
	libfribidi.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libfribidi.so.0 (0x00007f9d613c8000)
	libcairo-gobject.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libcairo-gobject.so.2 (0x00007f9d613bd000)
	libgdk_pixbuf-2.0.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgdk_pixbuf-2.0.so.0 (0x00007f9d6138f000)
	libepoxy.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libepoxy.so.0 (0x00007f9d61261000)
	libXi.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXi.so.6 (0x00007f9d6124b000)
	libwayland-client.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libwayland-client.so.0 (0x00007f9d61239000)
	libpng16.so.16 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libpng16.so.16 (0x00007f9d611f9000)
	libfreetype.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libfreetype.so.6 (0x00007f9d61126000)
	libXrender.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXrender.so.1 (0x00007f9d61119000)
	libxcb-render.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libxcb-render.so.0 (0x00007f9d61108000)
	libxcb-shm.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libxcb-shm.so.0 (0x00007f9d61103000)
	libpixman-1.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libpixman-1.so.0 (0x00007f9d61017000)
	libwayland-server.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libwayland-server.so.0 (0x00007f9d61001000)
	libxcb-randr.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libxcb-randr.so.0 (0x00007f9d60ff0000)
	libXau.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXau.so.6 (0x00007f9d60fe9000)
	libXdmcp.so.6 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXdmcp.so.6 (0x00007f9d60fe1000)
	libblkid.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libblkid.so.1 (0x00007f9d60f83000)
	libcryptsetup.so.12 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libcryptsetup.so.12 (0x00007f9d60f00000)
	libwayland-cursor.so.0 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libwayland-cursor.so.0 (0x00007f9d60ef6000)
	libwayland-egl.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libwayland-egl.so.1 (0x00007f9d60eef000)
	libXcursor.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libXcursor.so.1 (0x00007f9d60ee2000)
	libgraphite2.so.3 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libgraphite2.so.3 (0x00007f9d60eba000)
	libjpeg.so.62 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libjpeg.so.62 (0x00007f9d60dc9000)
	libbz2.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libbz2.so.1 (0x00007f9d60db4000)
	libuuid.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libuuid.so.1 (0x00007f9d60daa000)
	libdevmapper.so.1.02 => /auto/vestec1-elixir/projects/biocev/gentoo/lib64/libdevmapper.so.1.02 (0x00007f9d60d4f000)
	libargon2.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libargon2.so.1 (0x00007f9d60d45000)
	libjson-c.so.5 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libjson-c.so.5 (0x00007f9d60d32000)
	libudev.so.1 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libudev.so.1 (0x00007f9d60cf2000)
	libcap.so.2 => /auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/libcap.so.2 (0x00007f9d60ce6000)
$
```

Interestingly, I am puzzled how did I manage to compile rstudio if `media-video/ffmpeg` was not yet installed.


```
$ rstudio --disable-setuid-sandbox
Trace/breakpoint trap  (core dumped).
[716137:0808/175725.757040:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
$
```

I managed to get qtwebengine compiled in https://bugs.gentoo.org/911715 so I can now recompile `rstudio` with `qt5`.

**Comment by mmokrejs** [comment]
BTW, here is output from qt5-enabled rstudio:

```
$ rstudio 
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/auto/vestec1-elixir/projects/biocev/gentoo/etc/xdg/rstudio/logging.conf'. Logging to '/storage/vestec1-elixir/projects/biocev/mmokrejs/.local/share/rstudio/log/rdesktop.log'.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mmokrejs'
[726493:726539:0808/162050.042100:ERROR:command_buffer_proxy_impl.cc(141)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
```

Here is output from qt6-enabled rstudio:
```
$ rstudio 
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/auto/vestec1-elixir/projects/biocev/gentoo/etc/xdg/rstudio/logging.conf'. Logging to '/storage/vestec1-elixir/projects/biocev/mmokrejs/.local/share/rstudio/log/rdesktop.log'.
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
```
Anyway, seems they work (raise a window with a working R shell).

**Comment by jgenco** [comment]
On the `ffmpeg` thing, I currently use the official precompiled version of electron.
https://github.com/jgenco/jgenco-overlay/blob/4f3f038801665411a677c08ab68b35a8c3a5dbae/sci-mathematics/rstudio/rstudio-2023.06.1.524.ebuild#L146-L151
It is currently one of only two binary files in this repo. The other being `dev-lang/dart-bin`

Because of its size and complexity I just use the precompiled version.  Even (all?) electron apps in the ::gentoo use precompiled binaries.  There are [electron ebuilds](https://github.com/12101111/overlay/tree/master/dev-util/electron) that I assume work.  There is another repo but I don't have the link at the moment.  The big problem for me it takes ~15hrs to build `qtwebengine-6` and Electron uses Google's Chrome just like qtwebengine.

~~I hope installing `qtsv6` on your other bug gets you going.~~   I'm glad it works. I'll add  qtsvg dep later today or tomorrow.

**Comment by mmokrejs** [comment]
OK, thank you. If you think `electron` should be masked altogether by `Gentoo::Prefix` profile feel free to raise that. I do not have unfortunately time to investigate that.

**Comment by jgenco** [comment]
I have taken your suggestion of masking `electron` for rstudio.
  
As the USE issue is better described and qt problems are fixed; with your permission I would like change this issue to deal with the electron problem.  If you disagree you can close this issue.

**Comment by mmokrejs** [comment]
Well, I don't  understand the details but my impression was that on Gentoo-Prefix the SUID binaries cannot be even created. So, disabling it for such environment sounds good to me. I do not know for which env variable one should check to determine if the system is running on Prefix or not.

**Comment by jgenco** [comment]
Sorry  for taking so long to respond.  While its true SUID binaries can't be created on prefix systems.  Electron doesn't seem to need SUID set on Linux if the kernel has the [required options](https://github.com/gentoo/gentoo/blob/56535862e410c3a661248f9e2f94d24385af11db/eclass/chromium-2.eclass#L31-L47) set. I realize that on prefix systems the user is _not_ in control of the host kernel.

---

For example the following works fine running as a normal user. ([For different systems](https://posit.co/download/rstudio-desktop/))
```shell
cd /tmp
wget https://download1.rstudio.org/electron/jammy/amd64/rstudio-2023.06.2-561-amd64-debian.tar.gz
sha256sum rstudio-2023.06.2-561-amd64-debian.tar.gz
# d17dfb5c73ef32c2fbde7c80aadb2e9989333fa52c9e10f57403354af4903b70

tar xaf rstudio-2023.06.2-561-amd64-debian.tar.gz
cd rstudio-2023.06.2+561/

stat -c "%n - Access:%a/%A - UserID:%u GroupID:%g" rstudio chrome-sandbox
#rstudio - Access:755/-rwxr-xr-x - UserID:1000 GroupID:1000
#chrome-sandbox - Access:755/-rwxr-xr-x - UserID:1000 GroupID:1000

./rstudio
#"Mountain Hydrangea" Release (de44a311, 2023-08-25) for Ubuntu Jammy
#Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.2+561 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
```
This should work on a "normal" Linux install.  I _believe_ the needed options are enabled by default in most distros including Gentoo.

---

I haven't found any reference to Electron apps having problems with Gentoo prefix systems.  I would think some one would have used `app-editors/vscode`/`app-editors/vscodium`, or perhaps one of the various popular IM/chat/collaboration software based on Electron.

---

* This old [Reddit post](https://www.reddit.com/r/linux/comments/dvb43s/til_electron_requires_setuid_root_to_operate/) has some more information and links about Electron's sandboxing.
* Here is [Chromium's Official Docs](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux/sandboxing.md) about linux sandboxing.

**Comment by mmokrejs** [comment]
Thank you for your research on this. It was easy to repeat your steps:

```
stat -c "%n - Access:%a/%A - UserID:%u GroupID:%g" rstudio chrome-sandbox
rstudio - Access:700/-rwx------ - UserID:9999 GroupID:9999
chrome-sandbox - Access:700/-rwx------ - UserID:9999 GroupID:9999
mokrejs@dell_e5580$ ./rstudio
[14581:0909/090151.435332:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=desktop-gl,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[14581:0909/090151.436737:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[14625:0909/090151.800356:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=desktop-gl,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[14625:0909/090151.803893:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[14635:0909/090151.813032:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=desktop-gl,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[14635:0909/090151.819769:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[14617:0909/090151.925285:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

I ended up with an Rstudio main GUI windows but with an error message:

```
Error Starting R
The R session failed to start.

RSTUDIO VERSION
RStudio 2023.06.2+561 "Mountain Hydrangea " (de44a311, 2023-08-25) for Ubuntu Jammy
[No error available]
/tmp/rstudio-2023.06.2+561/resources/app/bin/rsession: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
OUTPUT
[No output emitted]
/home/mmokrejs/.local/share/rstudio/log/rsession-mmokrejs.log
2023-03-20T09:14:13.229605Z [rsession-mmokrejs] WARNING Abort requested; LOGGED FROM: bool rstudio::session::connection::checkForAbort(boost::shared_ptr<rstudio::session::HttpConnection>, boost::function<void()>) src/cpp/session/http/SessionHttpConnectionUtils.cpp:135
2023-03-20T09:14:13.229605Z [rsession-mmokrejs] WARNING Abort requested; LOGGED FROM: bool rstudio::session::connection::checkForAbort(boost::shared_ptr<rstudio::session::HttpConnection>, boost::function<void()>) src/cpp/session/http/SessionHttpConnectionUtils.cpp:135
```


```
$ ls -latr /usr/lib64/libssl*
-rwxr-xr-x 1 root root 687624 Sep  6 23:07 /usr/lib64/libssl.so.1.1
lrwxrwxrwx 1 root root     13 Sep  6 23:07 /usr/lib64/libssl.so -> libssl.so.1.1
-rwxr-xr-x 1 root root 478632 Sep  8 14:26 /usr/lib64/libssl3.so
```

```
# emerge -pv openssl

[ebuild   R    ] dev-libs/openssl-1.1.1v:0/1.1::gentoo  USE="asm rfc3779 verify-sig weak-ssl-ciphers -sctp (-sslv3) -static-libs -test -tls-compression -tls-heartbeat -vanilla" CPU_FLAGS_X86="(sse2)" 0 KiB
```

```
# emerge -pv rstudio

!!! All ebuilds that could satisfy "acct-user/rstudio-server" have been masked.
!!! One of the following masked packages is required to complete your request:
- acct-user/rstudio-server-0-r2::jgenco (masked by: package.mask)
/usr/portage/profiles/package.mask:
# Florian Schmaus <flow@gentoo.org> (2023-07-17)
# Obsolete acct-* packages which became leaf packages.
# Removal on 2023-08-17.

- acct-user/rstudio-server-0-r2::gentoo (masked by: package.mask)

(dependency required by "sci-mathematics/rstudio-2023.06.1.524::jgenco[server]" [ebuild])
(dependency required by "rstudio" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
#
```

Well, I am lucky that I managed to to get it compiled against qt5 and qt6 through your ebuild some while ago so I do not need to really study the electron part.

**Comment by jgenco** [comment]
Damn, I was going to mention OpenSSL 1.1/3.0 problem because I believe Posit has one for OpenSSL 1.1.  I just assumed you were running OpenSSL 3.0.  

FYI: [OpenSSL will reach EOL on 2023/9/11](https://packages.gentoo.org/packages/dev-libs/openssl)

I'll start a new issue for Electron on Prefix.
